site: Algorithmic expression⸷

url: https://mirtunio.github.io/gen_web_2025
baseurl: /gen_web_2025

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug
  writing:
    output: true
    permalink: /writing/:title/
  essays:
    output: true
    permalink: /essays/:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 50
paginate_path: "/blog/page:num/"

grid_alignments:
  - top
  - center
  - bottom